spring:
    application:
        name: order-service
    datasource:
        url: jdbc:postgresql://${POSTGRESQL_ORDERS_HOST:localhost}/orders
        username: ${POSTGRESQL_ORDERS_USERNAME:orders}
        password: ${POSTGRESQL_ORDERS_PASSWORD:orders}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: create